// <auto-generated />
using System;
using ApiWebsite.Core.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260107070951_DataQLDauThau")]
    partial class DataQLDauThau
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiWebsite.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DonViDeNghiId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLock")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Pseudonym")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Roles")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Salt")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("TimeLock")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("VerifacationCode")
                        .HasColumnType("NVARCHAR(10)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("ApiWebsite.Models.EmailConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("EmailTitle")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<bool>("EnableSSl")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MailServer")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Password")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmailConfig");
                });

            modelBuilder.Entity("ApiWebsite.Models.FileManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<int>("FileSizeInKB")
                        .HasColumnType("int");

                    b.Property<string>("FileType")
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("PhysicalPath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("PhysicalThumbPath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("ThumbPath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FileManager");
                });

            modelBuilder.Entity("ApiWebsite.Models.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("ApiWebsite.Models.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("LoginHistory");
                });

            modelBuilder.Entity("ApiWebsite.Models.LoginHistory", b =>
                {
                    b.HasOne("ApiWebsite.Models.Account", "Account")
                        .WithMany("LoginHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ApiWebsite.Models.Account", b =>
                {
                    b.Navigation("LoginHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
