// <auto-generated />
using System;
using ApiWebsite.Core.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302013723_fix")]
    partial class fix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiWebsite.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DonViDeNghiId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLock")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Pseudonym")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Roles")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Salt")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("TimeLock")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("VerifacationCode")
                        .HasColumnType("NVARCHAR(10)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("ApiWebsite.Models.BiddingProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStepOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProcessBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcessBranchId");

                    b.ToTable("BiddingProject");
                });

            modelBuilder.Entity("ApiWebsite.Models.EmailConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("EmailTitle")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<bool>("EnableSSl")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MailServer")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Password")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmailConfig");
                });

            modelBuilder.Entity("ApiWebsite.Models.FileManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<int>("FileSizeInKB")
                        .HasColumnType("int");

                    b.Property<string>("FileType")
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("PhysicalPath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("PhysicalThumbPath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("ThumbPath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FileManager");
                });

            modelBuilder.Entity("ApiWebsite.Models.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("ApiWebsite.Models.Logger.AuditLog.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("TableName")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR(250)");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("ApiWebsite.Models.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("LoginHistory");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProcessBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchCode")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("BranchName")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProcessBranch");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ProcessBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresAttachment")
                        .HasColumnType("bit");

                    b.Property<int>("SlaDays")
                        .HasColumnType("int");

                    b.Property<string>("StepCode")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("StepName")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<long>("TargetDonViId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcessBranchId");

                    b.HasIndex("TargetDonViId");

                    b.ToTable("ProcessStep");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProjectDataIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BiddingProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BiddingProjectId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldCode")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NumberValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ProjectStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectStepId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BiddingProjectId");

                    b.HasIndex("BiddingProjectId1");

                    b.HasIndex("ProjectStepId");

                    b.HasIndex("ProjectStepId1");

                    b.ToTable("ProjectDataIndex");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProjectFormSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BiddingProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BiddingProjectId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StepsSchemaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BiddingProjectId");

                    b.HasIndex("BiddingProjectId1");

                    b.ToTable("ProjectFormSchema");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProjectStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BiddingProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletedByUserId")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BiddingProjectId");

                    b.HasIndex("ProcessStepId");

                    b.ToTable("ProjectStep");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProjectStepAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtension")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("FileName")
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProjectStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectStepId");

                    b.ToTable("ProjectStepAttachment");
                });

            modelBuilder.Entity("ApiWebsite.Models.StepAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributeCode")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("AttributeName")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("InputType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProcessStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SelectOptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcessStepId");

                    b.ToTable("StepAttribute");
                });

            modelBuilder.Entity("ApiWebsite.Models.System.DonViDeNghi.DonViDeNghi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DonViDeNghi");
                });

            modelBuilder.Entity("ApiWebsite.Models.System.Permission.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Resource")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("RoleName")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("ApiWebsite.Models.Welcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Welcome");
                });

            modelBuilder.Entity("ApiWebsite.Models.BiddingProject", b =>
                {
                    b.HasOne("ApiWebsite.Models.ProcessBranch", "ProcessBranch")
                        .WithMany()
                        .HasForeignKey("ProcessBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessBranch");
                });

            modelBuilder.Entity("ApiWebsite.Models.LoginHistory", b =>
                {
                    b.HasOne("ApiWebsite.Models.Account", "Account")
                        .WithMany("LoginHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProcessStep", b =>
                {
                    b.HasOne("ApiWebsite.Models.ProcessBranch", "ProcessBranch")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiWebsite.Models.System.DonViDeNghi.DonViDeNghi", "TargetDonVi")
                        .WithMany()
                        .HasForeignKey("TargetDonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessBranch");

                    b.Navigation("TargetDonVi");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProjectDataIndex", b =>
                {
                    b.HasOne("ApiWebsite.Models.BiddingProject", null)
                        .WithMany()
                        .HasForeignKey("BiddingProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiWebsite.Models.BiddingProject", "BiddingProject")
                        .WithMany()
                        .HasForeignKey("BiddingProjectId1");

                    b.HasOne("ApiWebsite.Models.ProjectStep", null)
                        .WithMany()
                        .HasForeignKey("ProjectStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiWebsite.Models.ProjectStep", "ProjectStep")
                        .WithMany()
                        .HasForeignKey("ProjectStepId1");

                    b.Navigation("BiddingProject");

                    b.Navigation("ProjectStep");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProjectFormSchema", b =>
                {
                    b.HasOne("ApiWebsite.Models.BiddingProject", null)
                        .WithMany()
                        .HasForeignKey("BiddingProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiWebsite.Models.BiddingProject", "BiddingProject")
                        .WithMany()
                        .HasForeignKey("BiddingProjectId1");

                    b.Navigation("BiddingProject");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProjectStep", b =>
                {
                    b.HasOne("ApiWebsite.Models.BiddingProject", "BiddingProject")
                        .WithMany("ProjectSteps")
                        .HasForeignKey("BiddingProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiWebsite.Models.ProcessStep", "ProcessStep")
                        .WithMany()
                        .HasForeignKey("ProcessStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BiddingProject");

                    b.Navigation("ProcessStep");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProjectStepAttachment", b =>
                {
                    b.HasOne("ApiWebsite.Models.ProjectStep", "ProjectStep")
                        .WithMany("Attachments")
                        .HasForeignKey("ProjectStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectStep");
                });

            modelBuilder.Entity("ApiWebsite.Models.StepAttribute", b =>
                {
                    b.HasOne("ApiWebsite.Models.ProcessStep", "ProcessStep")
                        .WithMany("Attributes")
                        .HasForeignKey("ProcessStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessStep");
                });

            modelBuilder.Entity("ApiWebsite.Models.Account", b =>
                {
                    b.Navigation("LoginHistory");
                });

            modelBuilder.Entity("ApiWebsite.Models.BiddingProject", b =>
                {
                    b.Navigation("ProjectSteps");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProcessBranch", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProcessStep", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("ApiWebsite.Models.ProjectStep", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
